### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by lakluklak** [stijnherfst/HiveWE#87]
Hi! I'm trying to build the latest version, but when I follow the build guide step-by-step and open project in VS2022, I get this error:

C:/vcpkg/scripts/buildsystems/vcpkg.cmake:573(_add_executable):
target "hivewe" links to target "qt5::gui" but the target was not found. Perhaps a find_package() call is missing for an imported target, or an alias target is missing?

Can you help me how to build?

**Comment by BogdanW3** [comment]
QT-Advanced-Docking-System still uses qt5 by default, you will have to modify its vcpkg.json file to use qtbase instead of qt5-base, and remove the qt5-x11extras dependency if you want to make the port functional for non-windows as well

**Comment by lakluklak** [comment]
> QT-Advanced-Docking-System still uses qt5 by default, you will have to find and modify its vcpkg.json file in your vcpkg to use qtbase instead of qt5-base, and remove the qt5-x11extras dependency if you want to make the port functional for non-windows as well

Hi,  thanks for your help I got it and done that step.
But now I get another error when building the tool, I don't know much about C++ so don't know how to fix this. Can you help me check it out?

Error: LNK2019 - unresolved external symbol GetCascError referenced in function "public: class casc::File __cdecl casc::CASC::file_open(class std::filesystem::path const &)const " (?file_open@CASC@casc@@QEBA?AVFile@2@AEBVpath@filesystem@std@@@Z::<!CASC>)

**Comment by BogdanW3** [comment]
Ah, more of the vcpkg stuff being out of date 😄
extract this into the vcpkg/ports folder and it should be fixed: [casclib.zip](https://github.com/stijnherfst/HiveWE/files/9328874/casclib.zip)

**Comment by lakluklak** [comment]
> Ah, more of the vcpkg stuff being out of date 😄 extract this into the vcpkg/ports folder and it should be fixed: [casclib.zip](https://github.com/stijnherfst/HiveWE/files/9328874/casclib.zip)

Hi, Thanks to you, I built it successfully.
But now i get another error when running tool. It shows something like this:

This application failed to start because no Qt platform plugin could be initialised. Reinstalling the application may fix this problem.
![image](https://user-images.githubusercontent.com/74496820/184522752-ac389671-d367-4bd1-bbc0-2712d2ff8e83.png)

**Comment by BogdanW3** [comment]
I swear if anyone reads this thread, they're going to hate vcpkg 😄 
That is **also** an issue with VCPKG, namely that it doesn't copy over QT6 plugins over into the build directory.
Go to C:\vcpkg\installed\x64-windows, and copy the Qt6 folder over to the folder where the exe is

**Comment by lakluklak** [comment]
> I swear if anyone reads this thread, they're going to hate vcpkg 😄 That is **also** an issue with VCPKG, namely that it doesn't copy over QT6 plugins over into the build directory. Go to C:\vcpkg\installed\x64-windows, and copy the Qt6 folder over to the folder where the exe is

Hi, I done that but it still happen same error, here are my exe's folder. I don't know where I did wrong.

![image](https://user-images.githubusercontent.com/74496820/184546774-25208d02-7d50-483f-98ee-9e9020b47bc8.png)

**Comment by BogdanW3** [comment]
You copied from the Qt6 folder, instead of copying the folder itself, but it seems that worked anyway.
 As for it breaking on shaders and the SLK files, is your Data folder empty or does it have subfolders like "icons" "shaders" etc?
 What the guide recommended was to run VS as admin so it can symlink from that Data folder to HiveWE/Data, but you can just copy files from the HiveWE/Data folder into that Data folder.

**Comment by lakluklak** [comment]
> You copied from the Qt6 folder, instead of copying the folder itself, but it seems that might be semi-working. I still don't recommend it, you should have a Qt6 folder in that "release" folder, and plugins folder should be inside.
> 
> As for it breaking on shaders and the SLK files, is your Data folder empty or does it have subfolders like "icons" "shaders" etc? What the guide recommended was to run VS as admin so it can symlink from that Data folder to HiveWE/Data, but you can just copy files from the HiveWE/Data folder into that Data folder.

Hi, thanks for your answer.

I did copy the Qt6 folder into exe's folder, but when I ran tool, it will say that " could not find qt platform plugin windows in ". But when I copy the plugins in Qt6 folder, it's won't happen that error, instead, It happen like the 2nd picture.
And I did copy the Data folder in Release into Exe's folder but still happen the same error. So I don't know where did I wrong.

**Comment by stijnherfst** [comment]
Most of these issues were resolved by improving the build system and updating code. The only issue should be that you need to copy the `imageformats` and `platforms` folders from `C:\vcpkg\buildtrees\qtbase\x64-windows-rel\Qt6\plugins` to be next to the built .exe. The .exe will now be under `HiveWE/build/<release or debug>/`
